spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com/
          predicates:
            - Query=url,baidu

        - id: google_route
          uri: https://google.com/
          predicates:
            - Query=url,google